version: '3.8'
services:
  openvoice_app:
    image: ai-voice-studio
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-voice-studio
    volumes:
      - "~/Documents/Docker/ai-voice-studio:/app/output"
      - ".:/app"
    ports:
      - "7861:7861"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]